on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: bubbet/faby-actions/.github/workflows/dotnet-publish.yml@main

  release-thunderstore:
    needs: build
    uses: xoxfaby/actions/.github/workflows/thunderstore.yml@main
    with:
      version: ${{ needs.build.outputs.version }}
    secrets:
      THUNDERSTORE_TOKEN: ${{ secrets.THUNDERSTORE_TOKEN }}
